#<Password> your password to use sudo
#<username> your username on server
#<host> host group that script will run on
#<owner>:<group> owner:groupt for file ownership
- name: Setup Nginx repository and preferences, then install Nginx
  hosts: <host>
  become: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    ansible_become_pass: "<Password>"
  tasks:
    - name: Add Nginx signing key
      shell: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

    - name: Verify Nginx signing key
      shell: gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg

    - name: Add Nginx repository
      shell: echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
    
#    - name: Backup nginx Conf
#      shell: cd /etc/ && tar cfz /home/ubuntu/nginx.tar nginx

    - name: Add Nginx package preferences
      copy:
        content: |
          Package: *
          Pin: origin nginx.org
          Pin-Priority: 900
        dest: /etc/apt/preferences.d/99nginx
        owner: <owner>
        group: <group>
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      shell: apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install nginx