- name: Install Kubeadm 
  hosts: all
  become: yes
  vars_files:
    - ../vars/prepare.yml
  tasks:
    - name: Ensure ssh directory exist
      file: 
        path: /home/{{username}}/.ssh
        state: directory
        mode: 0700
        owner: "{{username}}"

    - name: Add ssh keys for passwordless Authentication
      ansible.builtin.copy:
        src: ../files&folders/privkey.pub
        dest: /home/{{ username }}/.ssh/authorized_keys
        mode: 0600
        owner: '{{username}}'
    
    - name: Update cache
      apt:
        update-cache: yes

    - name: Install required packages
      ansible.builtin.package:
        name:
          - git
          - net-tools
          - docker.io
          - docker-compose
        state: present
      ignore_errors: yes
    